### ISSUE TITLE
URL not getting hit properly

### ISSUE THREAD

**Issue by haakym** [GeneaLabs/laravel-caffeine#10]
I've got a form at the following URL:

```
http://localhost/myproject/public/report/tokenstring
```

If I leave the page open for the javascript to fire I get the following in my console:

```
GET http://localhost/genealabs/laravel-caffeine/drip 404 (Not Found)
```

Am I doing something wrong? If not, is there anyway to modify the URL? Or, could you possibly make the route named:

```php
Route::get('genealabs/laravel-caffeine/drip', [
    'as'   => 'genealabs.laravel-caffeine.drip',
    'uses' => LaravelCaffeineController::class . '@drip']
);
```

and reference the named route in the middleware file:

```
$content = str_replace('</body>', 
    "<script>setInterval(function(){var e=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject('Microsoft.XMLHTTP');e.open('GET','" 
        . route('genealabs.laravel-caffeine.drip') 
        . "',!0),e.send()}," 
        . config('genealabs-laravel-caffeine.dripIntervalInMilliSeconds', 300000) 
        . ");</script></body>", $content);
```

Any ideas? Thank you.

**Comment by mikebronner** [comment]
Hi @haakym, so sorry I missed your message. This issue should have been resolved in a previous update where the GET url has been updated. Please let me know if this is still an issue.

**Comment by haakym** [comment]
Hi @mikebronner no problem! I didn't try the update yet, however when I moved my project to the production environment it works fine.

When using my dev environment, I'm using wamp, the url doesn't seem to get hit properly perhaps because I have to add in `public` to the url? So this is pretty much a non-issue for me. Will hopefully give the update a try soon.

Thanks for your assistance and your work on the package!
