### ISSUE TITLE
What if the body tag is not closed?

### ISSUE THREAD

**Issue by tontonsb** [GeneaLabs/laravel-caffeine#105]
It seems in [the middleware](https://github.com/GeneaLabs/laravel-caffeine/blob/master/src/Http/Middleware/LaravelCaffeineDripMiddleware.php) that the code is inserted by replacing `'</body>'` with `"{$dripper->html}</body>"`.

However, according to [specs](https://www.w3.org/TR/html5/syntax.html#optional-tags) it is optional to close body:

> A body element’s end tag may be omitted if the body element is not immediately followed by a comment.

Am I missing something or is this just not working if the `</body>` is absent?

**Comment by mikebronner** [comment]
Correct, it currently will not work without the body closing tag. I don't think this is something I will invest time into addressing. If it is important to you, please submit a PR to address this. I could see a solution using clever DOM selector Syntax to get around all the optional tags.
