### ISSUE TITLE
Support for Laravel 5.8

### ISSUE THREAD

**Issue by aglipanci** [GeneaLabs/laravel-caffeine#107]
## Expected Behavior
The package should have support for Laravel 5.8
## Actual Behavior
Currently upgrading to Laravel 5.8 with this package is not possible.

## Environment
- PHP Version: 7.2
- Laravel Version: 5.8
- LaravelCaffeine Version: 0.7.1

**Comment by mikebronner** [comment]
Should be fixed in latest version. Let me know how that goes.
