### ISSUE TITLE
[Laravel 5.8] The page keeps reloading after package installation

### ISSUE THREAD

**Issue by wijourdil** [GeneaLabs/laravel-caffeine#108]
## Expected Behavior
I just have installed the package, in order to prevent token expiration on an ajax form

## Actual Behavior
The page on which I have the form keeps reloading

## Environment
- PHP Version: 7.2
- Laravel Version: 5.8
- LaravelCaffeine Version: 0.8.1

**Comment by mikebronner** [comment]
@wijourdil Can you provide a live example? If not, could you provide a video demonstrating the issue?

**Comment by mikebronner** [comment]
I'm not able to replicate this. Closing for now, please follow up with more details if you are still experiencing this issue.

**Comment by TheWiseNoob** [comment]
I'm having this same issue. I can't leave it as a live example because it makes the site unusable. I have to uninstall Laravel Caffeine to get the page to stop constantly refreshing.

**Comment by TheWiseNoob** [comment]
I'm using Laravel 6. I just updated so I could use this.

**Comment by mikebronner** [comment]
@TheWiseNoob Thanks for reporting that this is still happening for you. I will see if I can replicate this in Laravel 6.

**Comment by TheWiseNoob** [comment]
Since you're around at the moment, here is the test site for my client that I am having this issue with. I can leave it like this for an hour if you want to investigate it there if you're free now.

https://djgriffinwebtesting.dev/howtubes/public/

**Comment by TheWiseNoob** [comment]
What's weirder is my localhost installation of your package isn't having this problem, but it's also not updating the token. I set the session length to a minute and the refresh rate to 30 seconds, but it still mismatches on there.

**Comment by mikebronner** [comment]
@TheWiseNoob I just took a look at the site ... go ahead and disable it again, there's not too much I can look at since it constantly refreshes. Thanks for showing the behavior.

**Comment by mikebronner** [comment]
@TheWiseNoob I am unable to recreate this issue after installing it in a Laravel 6 project. It runs the Ajax drips without reloading the page.

Are you by any chance running your page as an SPA? Something else in your frontend must be conflicting.

**Comment by TheWiseNoob** [comment]
> @TheWiseNoob I am unable to recreate this issue after installing it in a Laravel 6 project. It runs the Ajax drips without reloading the page.
> 
> Are you by any chance running your page as an SPA? Something else in your frontend must be conflicting.

Yes, it is a single-page application.

**Comment by mikebronner** [comment]
@TheWiseNoob This package won't work with SPAs, unfortunately.

**Comment by TheWiseNoob** [comment]
Oh, I did not see that is the case. Sorry about that. What would be the best approach for refreshing the token in the case of a single-age app?

**Comment by mikebronner** [comment]
I can't answer that ... it depends completely on each SPA as to how state is managed. You would have to develop your own drip method, or perhaps see if you can find a way to make the package work with SPAs. :)

**Comment by TheWiseNoob** [comment]
Hmm, I might do that. Some more commits in my name would be very helpful for my career. Really appreciate you looking into this. I also found a good answer to my issue on StackOverflow.

https://stackoverflow.com/questions/31449434/handling-expired-token-in-laravel
