### ISSUE TITLE
Conflict with Voyager

### ISSUE THREAD

**Issue by meesudzu** [GeneaLabs/laravel-caffeine#110]
## Acutal Behavior

It's conflict with voyager 1.2.6.
Can't be load admin dashboard.

## Environment
- PHP Version: 7.2
- Laravel Version: 5.8
- LaravelCaffeine Version: 0.8.1
![image](https://user-images.githubusercontent.com/17334624/59838749-a8925900-9379-11e9-84a0-7654b226a962.png)

**Comment by mikebronner** [comment]
Hi @meesudzu, thanks for reporting this. I don't use Voyager, so if you could provide a PR that fixes this issue, that would be great.

**Comment by syclone** [comment]
Same issue here. I had to remove **laravel-caffeine** to use Voyager. I do not know why it is conflicting.

**Comment by syclone** [comment]
Hi @meesudzu, @mikebronner and anyone who is experiencing this issue. I was able to find a workaround to void the conflict.

**Workaround**: Configure the **laravel-caffiene** to use middleware `'use-route-middleware' => true,` and only apply that middleware to your main site. There are many ways to do that with a group route. Avoid having **laravel-caffiene** while voyager is active. You can use `php artisan caffeine:publish --config` to publish the config file.

This does not address the problem but allows me to utilize both when needed.

**Comment by mikebronner** [comment]
Updated readme with conflict warning, and mention of work-around.
