### ISSUE TITLE
Cannot install on latest laravel

### ISSUE THREAD

**Issue by rjsworking** [GeneaLabs/laravel-caffeine#113]
## Expected Behavior
Should be able to install on laravel 6.*

## Actual Behavior
Cannot install on L6.0.1 due to version constraints in composer.json

```
    "require": {
        "illuminate/routing": "6.0",
        "illuminate/support": "6.0",
     }
```

## Environment
- PHP Version: 7.3.9
- Laravel Version: 6.0.1
- LaravelCaffeine Version: latest

## Stack Trace
 Problem 1
    - Installation request for genealabs/laravel-caffeine ^1.0 -> satisfiable by genealabs/laravel-caffeine[1.0.0].
    - Conclusion: remove laravel/framework v6.0.1
    - Conclusion: don't install laravel/framework v6.0.1
    - genealabs/laravel-caffeine 1.0.0 requires illuminate/routing 6.0 -> satisfiable by laravel/framework[v6.0.0], illuminate/routing[v6.0.0].
    - Can only install one of: laravel/framework[v6.0.0, v6.0.1].
    - don't install illuminate/routing v6.0.0|don't install laravel/framework v6.0.1
    - Installation request for laravel/framework (locked at v6.0.1, required as ^6.0) -> satisfiable by laravel/framework[v6.0.1].

**Comment by mikebronner** [comment]
@rjsworking Thanks for the feedback! Sorry about that, missed the `^` in the version constraints. This should now be fixed in release 1.0.1.
