### ISSUE TITLE
Laravel 6.0 and 6.1 Support

### ISSUE THREAD

**Issue by darkperis** [GeneaLabs/laravel-caffeine#116]
Please add support for Laravel 6.1

**Comment by mikebronner** [comment]
Should be supported. What composer error are you getting?

**Comment by rjsworking** [comment]
I think the problem is ```jenssegers/model``` needs to be tagged with a new version.
Cheers

**Comment by mikebronner** [comment]
@rjsworking  Yea, that's definitely holding some of my projects up as well. I believe the necessary changes have been merged. Waiting for a release.

**Comment by rjsworking** [comment]
@mikebronner The workaround is fork the ```jenssegers/model``` package, update it's composer json to support L6.1 and use it in your projects/packages composer.json: "jenssegers/model": "dev-master".

**Comment by mikebronner** [comment]
@rjsworking This should now be fixed in 1.0.3. Please let me know how that works for you.

**Comment by mikebronner** [comment]
Try 1.0.4 ... made a mistake in pushing 1.0.3. Sorry about that.

**Comment by rjsworking** [comment]
Np. It's working. 
Thank you very much.
