### ISSUE TITLE
Question about package

### ISSUE THREAD

**Issue by thewebartisan7** [GeneaLabs/laravel-caffeine#118]
I check the code of package and I can't understand why all this code and not just a simple ping to an endpoint that doesn't return nothing before sessions expired time pass?

Because I tested to make a setTimeout function just around 10 seconds before session.lifetime expired and it works.  I set  session.lifetime to 1 minute and then usin below JS code the token never expired:

```js

function keepAlive() {
                    $.ajax({
                        url: '/ping',
                        method: 'post',
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    }).then(function (d) {
           
                        $('#infotoken').prepend('<div>' + new Date() + ' Token is: ' + d+ '</div>');
                    });

                    setTimeout(function () {
                        keepAlive();
                    }, 50000);
                }

                setTimeout(function () {
                    keepAlive();
                }, 50000);

```

```php

// the /ping route
Route::post('ping', function() {
    return csrf_token();
});

```

Seem token expire only if session.lifetime is higher after last use.

Thanks

**Comment by ivanvermeyen** [comment]
Hi,

I was asking myself the same question, but I think this is what it comes down to.

While you could implement the script manually on every page that has a form, this package does it automatically via middleware by checking if there is a `_token` field:

> To achieve this, we are sending a caffeine-drip (a request at regular intervals) to keep the session from timing out. This is only implemented on pages with a _token field, so all other pages will time-out as normal.

Something else I found in the config file is this:

> If the browser is put to sleep on (for example on mobile devices or laptops), it will still cause an error when trying to submit the form. To avoid this, we force-reload the form 2 minutes prior to session time-out or later. Setting this setting to 0 will disable this check if you don't want to use it.

So that's another part of the script to implement.

You can of course just do it manually.
This package just automates it all, which is really convenient :)

**Comment by mikebronner** [comment]
@ivanvermeyen answered it best! :) Hopefully this answered your question? Closing for now. I hope you find this package useful. :)
