### ISSUE TITLE
Issue in production when changing the drip endpoint url default

### ISSUE THREAD

**Issue by rjsworking** [GeneaLabs/laravel-caffeine#119]
## Expected Behavior
Expected HTTP 204 

## Actual Behavior
Get an HTTP 404

## Environment
- PHP Version: 7.4.2 + Opcache + Nginx 1.17.3
- Laravel Version: 6.14.0
- LaravelCaffeine Version: Latest 1.0.5

Say I change the drip endpoint url from `genealabs/laravel-caffeine/drip` to `ping` in the genealabs-laravel-caffeine.php config file.
It works as expected in my dev environment (Windows 10+PHP 7.4.2+Opcache+Nginx 1.17.8).
Thought the culprit could be opcache but after enabled it in the dev environment, it still working as expected.
In the production environment it only works ok with the default drip endpoint.
Also checked in production with a log message that the DripController is hitted but it returns an 404 HTTP error.
I don't know what else could be the problem.

Cheers

**Comment by mikebronner** [comment]
@rjsworking This is really hard to replicate. Is the URL this is happening on publicly accessible? Also, could you create a test repo that replicates the problem when you publish it to production?

**Comment by rjsworking** [comment]
Hi. Thank you for the reply. I'll create a test repo and a public url with exactly the same composer.json asap and see if the problem happens and I will share it with you.

Cheers

**Comment by mikebronner** [comment]
@rjsworking Awesome ... thanks. Let's hope we can drill down into this.

**Comment by rjsworking** [comment]
@mikebronner First of all, my apologies.
There is nothing wrong with your package.
About 3 weeks ago, I was playing on the production server with some nginx settings to exclude the requests generated by the package from the logs.
I completely forgot about these changes and last week, after the first deploy in production, errors started to appear. The errors happened for "live", "ping", "pop" routes, which were the locations that were on nginx. So I mistakenly assumed that it only worked for the default endpoint.
Case closed.

Cheers.

**Comment by mikebronner** [comment]
@rjsworking Awesome, glad to hear you figured it out! :)
