### ISSUE TITLE
Can't install in Laravel 7.0.1

### ISSUE THREAD

**Issue by JoshMountain** [GeneaLabs/laravel-caffeine#122]
## Expected Behavior
To be able to install the package

## Actual Behavior
Composer throws an error

## Environment
- PHP Version: 7.3.13
- Laravel Version: 7.0.1
- LaravelCaffeine Version: 7.0.0

## Stack Trace
![image](https://user-images.githubusercontent.com/3465855/75806021-264b9880-5d40-11ea-8d8c-d9699a46d2a0.png)

**Comment by mikebronner** [comment]
Hi @JoshMountain, sorry you're running into trouble. Unfortunately the dependency `jenssegers/model` has not yet updated to support Laravel 7. In the meantime, add the following repo to your project's `composer.json` file:
```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/GeneaLabs/model"
        }
    ],
```

Even though it is in this package's composer.json file, projects don't seem to respect repositories defined in packages. Once jenssegers/model is updated, I will update the dependencies here to no longer require my temp repo. If it takes too long for jenssegers/model to get updated, I will make mine a permanent fork.

Hope this helps, let me know how it goes. :)
