### ISSUE TITLE
Issue parsing inline javascript

### ISSUE THREAD

**Issue by aglipanci** [GeneaLabs/laravel-caffeine#124]
## Expected Behavior
The inline Javascript inside HTML should not be affected.

## Actual Behavior
The inline Javascript inside HTML is parsed and the closing tags are removed on the response causing JS errors.

## Environment
- PHP Version: 7.2.5
- Laravel Version: 7.1.0
- LaravelCaffeine Version: 7.0.1

## Steps to reproduce
1. Add the csrf-token meta inside the header: `<meta name="csrf-token" content="">`
2. Add some inline JavasScript containing HTML tags in the blade template: 
```
<script>
        var divOne = "<div>Content One</div>";
        var divTwo = '<div class="div-four">Content Two</div>';
    </script>
```

The template should look like this:
```
<!Doctype html>
<html class="no-js" lang="en">
    <head>
        <meta name="csrf-token" content=""/>
    </head>
    <body class="desktop">

    </body>
    <script>
        var divOne = "<div>Content One</div>";
        var divTwo = '<div class="div-four">Content Two</div>';
    </script>
</html>
```
3. Install Laravel-Caffeine and the output will be like this:
```
<!DOCTYPE html>
<html class="no-js" lang="en"><head>
        <meta name="csrf-token" content="">
    </head>
    <body class="desktop stockist-dashboard" data-gr-c-s-loaded="true">

    <script>
   // Dripper JS code here
    </script>

    <script>
        var divOne = "<div>Content One";
        var divTwo = '<div class="div-four">Content Two';
    </script>

</body></html>
```

If you notice the closing tags for the divOne and divTwo in JS are removed.

This behavior seems to be happening because of the `LaravelCaffeineDripMiddleware` middleware where the `HtmlPageCrawler` saveHtml method is called.

**Comment by mikebronner** [comment]
Thanks for the additional information @aglipanci !

Related to #123, I will continue discussion there if I can't get a fix in.

**Comment by mikebronner** [comment]
@aglipanci Specific to what you are seeing, I just tested, and it does not appear to be removing any closing tags.

**Comment by aglipanci** [comment]
@mikebronner did you add `<meta name="csrf-token" content="">` on inside the HEAD?

And add some Js like this:
```
<script>
   var divOne = "<div>Content One";
   var divTwo = '<div class="div-four">Content Two';
</script>
```

**Comment by mikebronner** [comment]
No, caffeine should not be adding any meta tags.

What I'm saying is that I specifically put in code that would not alter HTML in strings. Let me do a bit more testing.

**Comment by mikebronner** [comment]
yea, it looks like the HTML parser is buggy. 🤬 Will try to find one that works as expected.

**Comment by aglipanci** [comment]
Thanks for dealing with this @mikebronner!

**Comment by mikebronner** [comment]
@aglipanci Can you give release 7.0.2 a try and let me know how it works?

**Comment by aglipanci** [comment]
@mikebronner it's working fine now. Thanks for the quick fix!

**Comment by mikebronner** [comment]
@aglipanci Awesome! Thanks for reporting back :)
