### ISSUE TITLE
What's wrong with exposing the CSRF token?

### ISSUE THREAD

**Issue by dweerd** [GeneaLabs/laravel-caffeine#126]
You state: "I chose this approach to keep the integrity of site-security, by avoiding the following: exposing the CSRF Token on an unsecured endpoint."

But since the token is tied to a user session, anyone requesting the token would only see his own token... I don't see why that's a problem?

**Comment by mikebronner** [comment]
True ... the CSRF token is visible in the browser in most circumstances anyway. However, I would rather not rely on the CSRF token, in case it gets out of sync, etc. I've had too many issues in that regard.

Closing this issue, as this seems more of a comment than a bug report or feature request. Please feel free to reply and update this issue if you have additional information. Thanks! :)
