### ISSUE TITLE
Caffeine javascript is behind closing body-tag

### ISSUE THREAD

**Issue by funkdoobiest** [GeneaLabs/laravel-caffeine#127]
## Expected Behavior
Caffeine javacript is before closing body-tag.
## Acutal Behavior
Caffeine javascript is behind closing body-tag-
## Environment
- PHP Version: 7.4.5
- Laravel Version: 7.11.0
- LaravelCaffeine Version:  7.0.2

## Stack Trace

```
</body>
<script>
    var lastCheck = new Date();
    var caffeineSendDrip = function () {
        var ajax = window.XMLHttpRequest
            ? new XMLHttpRequest
            : new ActiveXObject('Microsoft.XMLHTTP');

        ajax.onreadystatechange = function () {
            if (ajax.readyState === 4 && ajax.status === 204) {
                lastCheck = new Date();
            }
        };

        ajax.open('GET', '/caffeine/drip');
        ajax.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
        ajax.send();
    };

    setInterval(function () {
        caffeineSendDrip();
    }, 300000);

    if (2000 > 0) {
        setInterval(function () {
            if (new Date() - lastCheck >= 7082000) {
                location.reload(true);
            }
        }, 2000);
    }
</script>
</html>
```

**Comment by mikebronner** [comment]
Hi @funkdoobiest, this actually was a conscious choice, even though it is not strictly standards compliant, it should work. Are you getting errors? If so, could you post them?

**Comment by funkdoobiest** [comment]
Hi @mikebronner,

just getting errors when validating my html. When this was a conscious choice that's ok.

Thank you for your fast reply :)

**Comment by mikebronner** [comment]
Yea, there were issues with the HTML parsing and optional closing body tags, and so on. For that matter, it still isn't bullet-proof if the developer does not close their HTML tags. I will continue to think about this. Thanks for bringing it up again.

**Comment by hashimaziz1** [comment]
Possibly relevant: https://github.com/mikebronner/laravel-caffeine/issues/139.
