### ISSUE TITLE
Dependency incompatibility issues for laravel 5 (and suspected 6)

### ISSUE THREAD

**Issue by lornacodes** [GeneaLabs/laravel-caffeine#128]
## Expected Behavior
Latest version should install for laravel 5.4 - I appreciate this is because of older packages I have that will not work with newer laravel versions.

## Actual Behavior
Latest version of laravel-caffeine does not install via composer (package incompatibilities)

I've noticed in one of the recent commits to composer.json there are the following requirements:

```
"illuminate/routing": "^7.0",
"illuminate/support": "^7.0",
```

Which I believe means only works if every other package you have is laravel 7 is compatible? (Some packages I have installed require "^5.0" versions.) Could this possibly be solved by having something like:

```
 "illuminate/contracts": "^5.0|^6.0|^7.0",
 "illuminate/support": "^5.0|^6.0|^7.0"
```

I can install laravel-caffeine 0.8.3 no problem!

## Environment
- PHP Version: 7.2.22
- Laravel Version: 5.4
- LaravelCaffeine Version: 7.0.2

## Stack Trace
Problem 1
    - Conclusion: remove laravel/framework v5.4.36
    - Conclusion: don't install laravel/framework v5.4.36
    - genealabs/laravel-caffeine 7.0.0 requires illuminate/routing ^7.0 -> satisfiable by illuminate/routing[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.2.0, v7.2.1, v7.2.2, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].

**Comment by mikebronner** [comment]
I apologize for the confusion. We dropped support for previous versions with the release of Laravel 7. You are free to fork the package and make the necessary changes to composer.json for your project.
