### ISSUE TITLE
Class web does not exist

### ISSUE THREAD

**Issue by MohamedQabbani** [GeneaLabs/laravel-caffeine#13]
When run route /genealabs/laravel-caffeine/drip
it return error 500  with ReflectionException in Container.php line 741:
Class web does not exist

**Comment by mikebronner** [comment]
@MohamedQabbani are you running on Laravel 5.2, or a lower version?

**Comment by MohamedQabbani** [comment]
@mikebronner i'm running on Laravel 5.1

**Comment by mikebronner** [comment]
What version of Caffeine do you have installed? Be sure you keep it at `0.2.*` or `~0.2.0`. The `0.3.x` versions are for Laravel 5.2 only.

**Comment by MohamedQabbani** [comment]
I run this command composer require genealabs/laravel-caffeine:~0.2

**Comment by mikebronner** [comment]
Run this: `composer require genealabs/laravel-caffeine:~0.2.0`. If you don't add the trailing `0` it will get the 0.3 version.

**Comment by MohamedQabbani** [comment]
ok i 'll

**Comment by mikebronner** [comment]
Fixed documentation in README as well as on forlaravel.com. Thanks again! :) I you still have issues, please re-open this issue and we'll investigate some more.
