### ISSUE TITLE
Failed Installation

### ISSUE THREAD

**Issue by JamesCobbledick** [GeneaLabs/laravel-caffeine#132]
## Expected Behavior
I'm expecting the package to install successfully.
## Acutal Behavior
Installation fails.
## Environment
- PHP Version: 7.4.1
- Laravel Version:  7.14.1
- LaravelCaffeine Version: 8.0

## Stack Trace
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for genealabs/laravel-caffeine ^8.0 -> satisfiable by genealabs/laravel-caffeine[8.0.0].
    - Conclusion: remove laravel/framework v7.14.1
    - genealabs/laravel-caffeine 8.0.0 requires illuminate/routing ^8.0 -> satisfiable by illuminate/routing[8.x-dev, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4, v8.1.0, v8.10.0, v8.11.0, v8.11.1, v8.11.2, v8.12.0, v8.12.1, v8.12.2, v8.
12.3, v8.13.0, v8.14.0, v8.15.0, v8.2.0, v8.3.0, v8.4.0, v8.5.0, v8.6.0, v8.7.0, v8.7.1, v8.8.0, v8.9.0].
    - don't install illuminate/routing 8.x-dev|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.0.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.0.1|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.0.2|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.0.3|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.0.4|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.1.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.10.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.11.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.11.1|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.11.2|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.12.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.12.1|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.12.2|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.12.3|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.13.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.14.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.15.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.2.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.3.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.4.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.5.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.6.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.7.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.7.1|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.8.0|don't install laravel/framework v7.14.1
    - don't install illuminate/routing v8.9.0|don't install laravel/framework v7.14.1
    - Installation request for laravel/framework (installed at v7.14.1, required as ^7.0) -> satisfiable by laravel/framework[v7.14.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by mikebronner** [comment]
Hi @JamesCobbledick, version 8 is only for Laravel 8. You would need to install an earlier version for 7.

**Comment by JamesCobbledick** [comment]
Thank you, that makes sense - I saw on the readme that "Laravel 7.0 or higher" was the dependency, so I wasn't sure.
