### ISSUE TITLE
not working for X-CSRF-TOKEN request header

### ISSUE THREAD

**Issue by shangsunset** [GeneaLabs/laravel-caffeine#14]
Hi, 

does this package also work for ajax request? its currently not working for me. i know it says it works for any page has `_token`, is ajax request included?

i did as laravel doc suggests:

```
<meta name="csrf-token" content="{{ csrf_token() }}">

$.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
});
```

update: i checked `LaravelCafineDripMiddleware.php`, and outputed `$content`. it turns out that the response content from my server is `array` instead of `string` since its not returning a view file. also it seems that the middleware is called twice. the first one returns `content` as  `string`, the second one returns `array`.

**Comment by mikebronner** [comment]
Yea, this is only for view forms. There are some scenarios where caffeine will process twice, but I haven't found s way around that yet.

**Comment by kxgen** [comment]
Same issue here.

**Comment by mikebronner** [comment]
Can you link me to the relevant code, or post an example in a GIST? Right now this only works with forms that has the token field added. Can you add the token field to the form?

**Comment by kxgen** [comment]
@mikebronner [gist here](https://gist.github.com/kxgen/4445a155273e5ed4ae90)

**Comment by mikebronner** [comment]
What if you changed your code like so:

```
    return `(
      <div id="container">
        <h3>Import playlist</h3>
        <form><input type="hidden" name="_token" value="' + $('meta[name="csrf-token"]').attr('content') + '"></form>
        <input type="text" ref="url" />
        <button onClick={this.handleSubmit}>Submit</button>
      </div>
    )`
```

Sure, it's a work-around, but this package isn't designed for pure AJAX forms, it depends on a form with the CSRF token being on the page, not in JavaScript.

**Comment by kxgen** [comment]
It works, and I made the following changes:

1.Add a form to html
```
<form><input type="hidden" name="_token" value="{{ csrf_token() }}"></form>
```
2.Use the token value from hidden input when sending an ajax request
```
$.ajax
      headers: 'X-CSRF-TOKEN': $('input[name="_token"]').attr('value')
```


And I add some script to `LaravelCaffeineDripMiddleware.php`, cause the variable `$content` always return null value (???):
```
if (method_exists($response, 'getOriginalContent')) {
    $content = (String) $response->getOriginalContent();
}
```

**Comment by mikebronner** [comment]
Are you running on L5.2? This is likely due to the route not being in the web middleware group. I will have to think about ways to have this work on all middleware groups.

**Comment by kxgen** [comment]
I am running on L5.1.

Thanks :)

**Comment by mikebronner** [comment]
done some more thinking on this and I think I have a solution. will post something in the next few days.

**Comment by mikebronner** [comment]
Just pushed update that should work on pages with the meta tag, no more fake forms! :)

**Comment by cillosis** [comment]
@mikebronner Thanks for this fix, you are a real life saver!. Any chance this can be updated on the Laravel 5.1 version as well? My understanding is 0.3 is only for L5.2 correct?

**Comment by mikebronner** [comment]
You might try installing it in L5.1 and see if it works. Chances are it will, since I now continue as normal if there is no "web" route middleware.

**Comment by cillosis** [comment]
Ah yes, that was what it had complained about before. I will give it a try and let you know.

**Comment by cillosis** [comment]
Appears to work fine! I guess that means you don't have two separate versions to maintain :+1: 

Thanks again, this is awesome.

**Comment by cillosis** [comment]
Edit: I retract that statement -- appears to not work exactly.

![image](https://cloud.githubusercontent.com/assets/1303759/13060664/17473dac-d401-11e5-9f2e-dd79eaf9450f.png)

**Comment by shangsunset** [comment]
Hi Mike,
Thanks for the update, the package works with Ajax now. However, using meta tag for Ajax means all pages will be 'awake' as meta tag will be set in a main layout file and all partial views under it will be affected. In my case, I'm using react as my view, so basically the whole site will be awake. Is there a workaround for this? 

Thanks

**Comment by mikebronner** [comment]
I guess you could use a view composer to conditionally render the meta tag? Or perhaps use a blade include only on the pages that need it by creating a meta placeholder in the layout, and only populating it on the respective pages that need it?

**Comment by cillosis** [comment]
@shangsunset If I were you, in my layout I would do something like:
 
    <meta>

           
          <title>My Site</title>

          
          @yield('meta')

    </meta>

Then in the view you might have something like:

    @extends('layout')

    @section('meta')
          
    @endsection

    @section('content')
          
    @endsection

That allows you to override as @mikebronner suggested

**Comment by mikebronner** [comment]
@cillosis thanks for detailing that, exactly what I meant :)

**Comment by shangsunset** [comment]
@mikebronner @cillosis Thanks for your suggestions. They are good solutions for sites have multiple view pages. but for a site uses react as its view, it only needs on blade file, which is the layout file.

**Comment by mikebronner** [comment]
For SPA's you would want it to refresh all the time, as its really only a single page. If you don't keep it refreshed for all pages in the SPA (Single Page App), the forms will no longer work when you get to a form if the session timed out. What is your use case that makes you want to not keep the forms awake?

**Comment by shangsunset** [comment]
I want to keep forms awake, but users session wont expire even though they didnt check 'remember me'.

**Comment by mikebronner** [comment]
That is the intended behavior. User sessions will expire after they logout or close the site and don't access their session for the given timeout period (default is 120 minutes set in `config/session.php`).

**Comment by shangsunset** [comment]
ohh i see. thank you!
