### ISSUE TITLE
Deprecation warning using with PHP 8.1

### ISSUE THREAD

**Issue by liepumartins** [GeneaLabs/laravel-caffeine#143]
## Expected Behavior

No warnings

## Actual Behavior

Deprecation warning

## Environment
- PHP Version: 8.1
- Laravel Version: 9.3.1
- LaravelCaffeine Version: 9.0.2

## Stack Trace
```
LOG.warning: trim(): Passing null to parameter #1 ($string) of type string is deprecated in 
/home/vagrant/laravel9/vendor/genealabs/laravel-caffeine/src/Dripper.php on line 41
```

**Comment by liepumartins** [comment]
Config file defines key `domain` as `null` by default.
https://github.com/GeneaLabs/laravel-caffeine/blob/4df612b77e08cd7d93eee79ed74bbf2f7ca1ff4a/config/genealabs-laravel-caffeine.php#L32

I have not customized this setting.

**Comment by mikebronner** [comment]
Ah, yes, thanks!
