### ISSUE TITLE
Not Working in Production environment 

### ISSUE THREAD

**Issue by hansajith1998** [GeneaLabs/laravel-caffeine#146]
## Expected Behavior
Run drip 5min interval 

## Actual Behavior
Not firing middleware in the production server.

## Environment
- PHP Version:  8.1 run with `php_sapi_name()` => litespeed
- Laravel Version:  9.5
- LaravelCaffeine Version: 9.0.3

**Comment by mikebronner** [comment]
@hansajith1998 could you provide a sample repository that reproduces this issue?

**Comment by hansajith1998** [comment]
I cannot reproduce this issue because my local machine will work smoothly with this package. When I upload to the server then this will stop working. I viewed the package Service class and I found php_sapi_name() checked before publishing middleware.
The only thing I was able to find is the production server runs on  `php_sapi_name()` => `litespeed`. 

![image](https://user-images.githubusercontent.com/64520856/223467099-b4929230-1d97-479e-a211-f27d8ec7d114.png)

Also, I have tried adding `litespeed` to the middleware check. after the issue is solved. 

![image](https://user-images.githubusercontent.com/64520856/223470165-76ff8dd7-774b-405c-9c2c-c5f7f966ea33.png)

Can you please add this fix to the next release?

**Comment by mikebronner** [comment]
ah, I see, thanks for the clarification.

**Comment by mikebronner** [comment]
Fixed in 9.0.4
