### ISSUE TITLE
Exposing the CSRF Token on an unsecured endpoint

### ISSUE THREAD

**Issue by olimorris** [GeneaLabs/laravel-caffeine#15]
Hi Mike,

Firstly I'm a big fan of the package and many thanks for your work

I just wanted to test some logic with regards to exposing the CSRF token on an unsecured endpoint. I'm using VueJS alongside Laravel to create an application and I like to use Laravel to generate a token in the `<script>` section of my `<head>` tags. This is of course subjected to token mismatch exceptions when the CSRF times out. I'm ideally trying to find a solution whereby I can keep those tokens refreshed and the most simplest would be to hit a route which serves up the CSRF token.

My question though, is do you believe there are any security issues with having a route which just serves CSRF tokens?

**Comment by mikebronner** [comment]
Hi @olimorris, I;ve been thinking about this as well. Initially I thought that exposing the CSRF token publicly would be a security risk, but if you add the csrf-token as a meta tag or in a hidden field, you expose it anyway. So not so sure about this. 

Laravel recommends using it as a form field or meta tag in the <head> of the HTML document. I would recommend sticking with those two. I am updating this package to work with both methods (previously it would not work with the meta tag).
