### ISSUE TITLE
Unusual laravel directory structure (or .htaccess) messes up routing

### ISSUE THREAD

**Issue by callumhay** [GeneaLabs/laravel-caffeine#18]
The url utilized by the middleware is using a path that assumes routing paths for laravel are not changed via .htaccess or other means. This causes the drip logic to not find the controller. The solution is to use the url function to make sure the path is correct.

My fix:
Replace line 32 of LaravelCaffeineDripMiddleware.php with the following:

`$content = str_replace('</body>', "<script>setInterval(function(){var e=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject('Microsoft.XMLHTTP');e.open('GET','".url('/genealabs/laravel-caffeine/drip')."',!0),e.send()}," . config('genealabs-laravel-caffeine.dripIntervalInMilliSeconds', 300000) . ");</script></body>", $content);`

**Comment by mikebronner** [comment]
Thanks for reporting this. I will look into this and the other issues later today. :)

**Comment by mikebronner** [comment]
Integrating this now.
