### ISSUE TITLE
404 error on drip

### ISSUE THREAD

**Issue by markustenghamn** [GeneaLabs/laravel-caffeine#21]
I believe it may be related to #10

I just installed this on Laravel 5.2 and configured it according to the instructions on the main page. I left a page up for a while and it gave me a 404 error when trying to call http://mydomain/genealabs/laravel-caffeine/drip

Visiting the url also gives 404.

Could perhaps adding the url to the routes.php file fix this issue?

**Comment by mikebronner** [comment]
Can you check if this is fixed in release 0.3.4?
