### ISSUE TITLE
Undefined index: middleware

### ISSUE THREAD

**Issue by olimorris** [GeneaLabs/laravel-caffeine#24]
**System:** Laravel 5.2.20 / PHP 7.0.2

With the latest commit, I'm getting the following error:
  
![screen shot 2016-02-20 at 17 04 33](https://cloud.githubusercontent.com/assets/9512444/13197959/1d55d7e8-d7f4-11e5-81f0-b6df0f160468.png)

It's solved by changing the `routes.php` file to:

```
if (isset(Route::getMiddleware()['web'])) {
```

**Comment by mikebronner** [comment]
Should be fixed in version 0.3.5
