### ISSUE TITLE
Working with Content Security Policy

### ISSUE THREAD

**Issue by bmcgoffin** [GeneaLabs/laravel-caffeine#27]
Greetings,

I am implementing CSP (content security policy) within my project and realized the policy is blocking the caffeine script from running.  I could add 'unsafe-eval' but wouldn't this open up the possibility of XSS attacks (ref: http://stackoverflow.com/questions/8502307/chrome-18-how-to-allow-inline-scripting-with-a-content-security-policy)?  I've attached 3 images (1st is the CSP, 2nd is the error message, 3rd is the script inline).  What I have done with my other scripts is put them in a separate .js file and include them in the header.   

One idea might be to move the script into a .js file then add a script src = "caffeine.js" on the pages needing this?  Thoughts?
![csp1](https://cloud.githubusercontent.com/assets/14063073/14570223/fb435606-02f7-11e6-8044-d584ad63dc59.PNG)
![csp2](https://cloud.githubusercontent.com/assets/14063073/14570226/ff1050e0-02f7-11e6-901f-15f32002f794.PNG)
![csp3](https://cloud.githubusercontent.com/assets/14063073/14570229/023d432c-02f8-11e6-8b68-c5b73dfc24b3.PNG)

**Comment by mikebronner** [comment]
Don't forget the images :) Thanks for posting the issue :)

**Comment by bmcgoffin** [comment]
Mike, updated the post to show the images, thanks!

**Comment by mikebronner** [comment]
Thanks -- I will take a look at this over the weekend and see what can be done. Thanks again for bringing this up! :)

**Comment by mikebronner** [comment]
@bmcgoffin I am unable to reproduce this. I'm not sure I understand completely, but Caffeine shouldn't be triggering a CSP warning, since its on the same domain? Can you provide steps to reproduce? I have installed `stevenmaguire/laravel-middleware-csp` and set the middleware on my default test route, like so:

```php
Route::group(['middleware' => ['web', 'secure.content']], function () {
    Route::get('/', function () {
        return view('welcome');
    });
    Route::post('/', function () {
        return view('welcome');
    });
});
```

**Comment by mikebronner** [comment]
Please re-open this issue if the problem persists. I will close it for now, since I didn't hear back and have been unable to reproduce it.
