### ISSUE TITLE
Configurable route

### ISSUE THREAD

**Issue by Propaganistas** [GeneaLabs/laravel-caffeine#28]
Why didn't you incorporate the configurable route as proposed in #9? This is really a huge bummer for me and makes me fork your package for just this small change.

**Comment by mikebronner** [comment]
Hi @Propaganistas, I'll look into it this weekend. Thanks for bringing it up again and letting me know it really is something that is needed. I was on the fence for a one-off, but if its something that prevents people from using the package, no problem.

Thanks! :)
~Mike

**Comment by mikebronner** [comment]
@Propaganistas I would like to understand your use-case a bit more, as to why you need configurable routes. (The current implemtation should not collide with any other routes, and its not a public route visible in the browser's address bar.)

I'm not against doing this, however, I would like to better understand the reasoning why this is needed. (This will help me greatly going forward with this and other packages.)

Thanks!
~Mike

**Comment by Propaganistas** [comment]
Hi @mikebronner. The reason is actually plain simple: the current route is branded with your company name. And inspite the route isn't publicly visible in the address bar, it does get printed in a page's source code.

**Comment by mikebronner** [comment]
Fixed in release 0.3.10

**Comment by Propaganistas** [comment]
Great, thanks!

**Comment by larsbo** [comment]
Another problem with the hard-coded route is that it doesn't work for laravel installations in subdirectories because the route starts with a `/`.

What about adding the configurable route to the 0.2.x branch for laravel 5.1 users?

**Comment by mikebronner** [comment]
@larsbo: moved to new issue #34. Makes sense.
