### ISSUE TITLE
Get rid of the middleware

### ISSUE THREAD

**Issue by garygreen** [GeneaLabs/laravel-caffeine#30]
Just out of curiosity, why does there need to be a middleware? Can't there just be one JavaScript file you include which will check the HTML on ready for a `<meta>` or `<input>` tag with token?

I personally don't like having too many intercepting middlewares altering the output etc, would much prefer a tiny bit of vanilla js included in each page checking a few tags.

**Comment by mikebronner** [comment]
The point of this package is to make it a drop-in solution where the developer doesn't need to do any additional config or setup. This is not meant to be a solution for everyone, and I completely understand if it doesn't fit your use case. :)
