### ISSUE TITLE
Add warning session is expiring

### ISSUE THREAD

**Issue by garygreen** [GeneaLabs/laravel-caffeine#32]
This package is focused around always keeping forms alive, a bit of a security problem imo that's why the whole expiry thing is default in Laravel.

It would be nice to have an option where the user is prompted (via a model alert) when the session is about to expire and give them a button to stay active (essentially sending the 'drip'). This is a similar same way the banking industry handle form/session expiration.

The way the alert is shown to the user of course will be subjective and need to be styled per app, but if caffeine made it relatively generic and exposed some options or api of events to easily show a custom alert it would be nice.

```js
LaravelCaffeine.start({
	alertText: 'Your session is about to expire.',
	btnText: 'Click to Continue'
});

LaravelCaffeine.expiring(function(drip) {
	// Show custom model and call 'drip' if button was pressed.
});
```

**Comment by mikebronner** [comment]
Hi @garygreen, yes, I am familiar with that approach as well, and thought about something similar while developing this package. However, it's a slightly different use case, and as such don't feel it should be included in this package.

I have had need for the session-count-down option as well though, so perhaps I'll create a package for that sometime down the road if I come across a project that calls for it again.

Thanks for your feedback :-)
