### ISSUE TITLE
Am I do it wrong?

### ISSUE THREAD

**Issue by reefki** [GeneaLabs/laravel-caffeine#33]
I set the session life time to one minute to test it out, my app is SPA with vuejs so instead of using laravel caffeine middleware I use following code to send drip:

```
setInterval(function () {
     Vue.http.get('/api/drip');
 }, 10000);
```

I define a new drip route like so:

```
$router->get('api/drip', '\GeneaLabs\LaravelCaffeine\Http\Controllers\LaravelCaffeineController@drip');
```

I see that in network tabs it sends the drip every 10 seconds, I leave the page open for a while after filled the form and after few minutes hit the submit button and I still get token mismatch exception. Am I missing something?

**Comment by ivanvermeyen** [comment]
is your route using the "web" middleware group, so it knows about the session?

**Comment by reefki** [comment]
Yes, in Laravel 5.2 the `web` middleware is automatically applied to all routes.

**Comment by ivanvermeyen** [comment]
Are you sending the CSRF token with the Vue request?
Answer found on [this post](https://laracasts.com/discuss/channels/laravel/processing-ajax-requests-from-vuejs):


Put this in the `<head>` element:

```html
{{-- This is the token Laravel requires for non-GET requests --}}
<meta id="_token" value="{{ csrf_token() }}"> 
```

If you are using the Vue http lib, use this code to include the token:

```javascript
Vue.http.headers.common['X-CSRF-TOKEN'] = document.querySelector('#token').getAttribute('value');
```

If you are using jQuery, use this code:

```javascript
<script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
</script>
```

This will automatically send the token with each request.

**Comment by mikebronner** [comment]
Hi @reefki, unfortunately this package isn't really built for SPAs. If you want to keep an SPA from timing out, it's best to increase the lifetime of the session. The only benefit this might have is that your session will never time out, as long as the browser is open.

Also, no need to create a route another route. Use the route provided in the package. In the configuration you have the option of overriding the default route for Caffeine, but that route should not exist in your app, the package will use that to create its own route for you.

@ivanvermeyen thanks for helping @reefki out! :)

**Comment by mikebronner** [comment]
Just as a side-note:I am considering implementing functionality that will work better with SPAs going forward, as I am adopting them more often as well, but haven't given it too much though yet.

**Comment by reefki** [comment]
@ivanvermeyen Thanks for your reply. Yes, I include the token via interceptor:

```
Vue.http.interceptors.push(function (request, next) {
    request.headers['X-CSRF-TOKEN'] = document.querySelector('meta[name="csrf_token"]').getAttribute('content');

    next(function (response) {
        return response;
    });
});
```

The form is working if the `csrf_token` still valid. As I said in the beginning the problems occurs if the token has expired.

@mikebronner I think it should be work either SPA or non SPA as long the app sending drip, right?

Thanks for the tips about Caffeine route, but since a SPA is using wildcard route and I set the url to non hashbang `!#` I still have to define a new route because using Caffeine route makes the AJAX request redirected to index page.

**Comment by mikebronner** [comment]
@reefki the package should be creating the route on the PHP server side of things. You don't need to create a route in your SPA, since that's only for client functionality. Or am I understanding the scenario incorrectly? If you don't create a route, what error do you get?

**Comment by reefki** [comment]
@mikebronner No, I didn't create drip route on the frontend, see on initial post I defined a new route on `routes.php`.

I've tried to use the Caffeine route `http://app.dev/genealabs/laravel-caffeine/drip` but instead of returning `204` status code the server redirect the request to the wildcard route and return `200` status code. See image below, the response contains code from `index.blade.php`.

![drip](https://cloud.githubusercontent.com/assets/10998084/17456589/37a64e7e-5c07-11e6-9f74-b42bd78825dd.png)

Here is my `routes.php`:

```
$router->any('{any}', function () {
    return view('index');
})->where('any', '.*');
```

**Comment by mikebronner** [comment]
@reefki, thanks prividing the details of the router and the response. The problem is that you have an "any" route defined that will respond to any request. That's not something I would ever recommend doing, it makes a whole bunch of assumptions. I would only create the route that is valid for your SPA, and return 404 for anything else that is not a valid route.

What's happening here is that your route is hijacking all incoming requests, and not letting any other routes take a stab at them. Once you get away from a wildcard route, the drip will work again.

**Comment by reefki** [comment]
@mikebronner The "any" wildcard is something that really important in my app, I wouldn't mind to define my 50+ routes both on `routes.php` and `routes.js`, a SPA only requires one page to be rendered once it's loaded which is `index.blade.php` in my case. If I follow your advice:

>I would only create the route that is valid for your SPA, and return 404 for anything else that is not a valid route.

It would only makes my `routes.php` full of redundant:

```
$router->get('/', function () {
    return view('index');
});

$router->get('/abc', function () {
    return view('index');
});

$router->get('/xyz', function () {
    return view('index');
});

// the rest here (about 47 routes)
```

Remember, as I said earlier my app is using HTML5 History API for the router instead of `!#`so if I define one route `/` only in `routes.php` then when visitor access my other pages that I've defined on my `routes.js` for example `http://app.dev/pages/contact` they will redirected to `404` page because that route isn't defined on `routes.php`. I think catch all route using `any` wildcard is the best option for me.

**Comment by mikebronner** [comment]
Thanks for the clarification on your use-case. Unfortunately, I would recommend you not use Laravel Caffeine at this time, as it provides no real benefit to you. Right now, the way it works with SPAs is the exact same effect as setting sessions to a large expiration. I think that is the better solution for you at this point.

Sorry, I know this wasn't the answer you are looking for, but Laravel Caffeine wasn't designed for SPAs, as those rely heavily on their JS framework for routing.

I will close this for now, and will continue to evaluate how Laravel Caffeine could be implemented for SPAs.

Best of luck!
