### ISSUE TITLE
https not http for the dripper

### ISSUE THREAD

**Issue by allotmentandy** [GeneaLabs/laravel-caffeine#35]
hi,

i want to know how to force the caffeine dripper to use a https url instead of a http? is there a way to add a setting FORCE_HTTPS? 

kind regards

Andy

**Comment by mikebronner** [comment]
The drip url is generated using the `url()` helper, which gets the base url from Laravel. This means it will use the same schema as your Laravel app is configured to use.

Do you have a use-case where you wouldn't want it to behave this way? (If your Laravel app is on HTTPS, but drip is not pointing to HTTPS, my guess is there is probably a configuration issue in your Laravel app.) Please let me know. :) 

Thanks!
~Mike

**Comment by allotmentandy** [comment]
hi, thanks for the reply.

i have the laravel app running behind a load balancer. so the internal laravel system is http but the client facing part is https. 

i have changed the line in the middleware to just call
$dripUrl = '/genealabs/laravel-caffeine/drip';

as the url part is broken, when i use the load balancer. 

but it is going to break when there is an update!

Andy

**Comment by mikebronner** [comment]
Excellent use case, I forgot to consider that! Thanks for bringing this up, I will add that as a configuration option.

**Comment by allotmentandy** [comment]
could you just have a full url in the config file?

**Comment by mikebronner** [comment]
Will definitely consider it. It will probably be two config values, one for the base URL (schema and domain) and another for the actual route on the app.

**Comment by allotmentandy** [comment]
yes, perhaps you can have url() as the default for the first one, so i can overright it.

thanks for a great package and great service.
