### ISSUE TITLE
Make Laravel5.3-Compatible

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-caffeine#37]

**Comment by kjfdebruin** [comment]
What's the current state of compatibility with 5.3?

**Comment by mikebronner** [comment]
@kjfdebruin It should theoretically work, I just haven't tested it yet ... have you tried it? I'm working on some internal optimizations and am testing with L5.3 this weekend, but let me know how it goes with the current version. :)

**Comment by mikebronner** [comment]
Should be working now. Please check out version 0.4.0 (which includes optimizations and installation changes, be sure to read the readme). Let me know how it works.
