### ISSUE TITLE
Domain url('/') breaks artisan optimize

### ISSUE THREAD

**Issue by Kyosfonica** [GeneaLabs/laravel-caffeine#39]
The domain => url('/') setting is breaking Laravel 5.2 artisan command.

The website works, but the artisan command crashes with a routing error.

PHP Catchable fatal error:  Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 62 and defined in /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 103

**Comment by mikebronner** [comment]
hi @Kyosfonica thanks for repoting the issue! Can you attach the full stack trace of the error, please?

**Comment by Kyosfonica** [comment]
Hi,

Sure, here it is. I have published the config file so its home is /config. But all configs are default.

I hope it helps

vagrant@homestead:~/Code/salunet$ php artisan optimize
PHP Catchable fatal error:  Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 62 and defined in /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 103
PHP Stack trace:
PHP   1. {main}() /home/vagrant/Code/salunet/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/vagrant/Code/salunet/artisan:36
PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:105
PHP   4. Illuminate\Foundation\Application->bootstrapWith() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:219
PHP   5. Illuminate\Foundation\Bootstrap\LoadConfiguration->bootstrap() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:203
PHP   6. Illuminate\Foundation\Bootstrap\LoadConfiguration->loadConfigurationFiles() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:38
PHP   7. require() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:60
PHP   8. url() /home/vagrant/Code/salunet/config/genealabs-laravel-caffeine.php:5
PHP   9. app() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:736
PHP  10. Illuminate\Foundation\Application->make() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:105
PHP  11. Illuminate\Container\Container->make() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
PHP  12. Illuminate\Container\Container->build() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
PHP  13. Illuminate\Container\Container->Illuminate\Container\{closure}() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
PHP  14. Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Container/Container.php:289
PHP  15. Illuminate\Routing\UrlGenerator->__construct() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php:62

Catchable fatal error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 62 and defined in /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 103

Call Stack:
    0.0003     225488   1. {main}() /home/vagrant/Code/salunet/artisan:0
    0.1299    2493728   2. Illuminate\Foundation\Console\Kernel->handle() /home/vagrant/Code/salunet/artisan:36
    0.1299    2493856   3. Illuminate\Foundation\Console\Kernel->bootstrap() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:105
    0.1299    2494024   4. Illuminate\Foundation\Application->bootstrapWith() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:219
    0.1420    2627080   5. Illuminate\Foundation\Bootstrap\LoadConfiguration->bootstrap() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:203
    0.1479    2656000   6. Illuminate\Foundation\Bootstrap\LoadConfiguration->loadConfigurationFiles() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:38
    0.2148    3117384   7. require('/home/vagrant/Code/salunet/config/genealabs-laravel-caffeine.php') /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:60
    0.2148    3117792   8. url() /home/vagrant/Code/salunet/config/genealabs-laravel-caffeine.php:5
    0.2148    3118048   9. app() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:736
    0.2148    3118232  10. Illuminate\Foundation\Application->make() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:105
    0.2148    3118232  11. Illuminate\Container\Container->make() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    0.2148    3118312  12. Illuminate\Container\Container->build() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    0.2148    3118344  13. Illuminate\Container\Container->Illuminate\Container\{closure}() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
    0.2148    3118512  14. Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Container/Container.php:289
    0.2290    3525648  15. Illuminate\Routing\UrlGenerator->__construct() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php:62

**Comment by mikebronner** [comment]
Thanks, can you also post your caffeine config file? :)

**Comment by Kyosfonica** [comment]
<?php

return [
    'dripIntervalInMilliSeconds' => 300000,
    'domain' => url('/'),
    'route' => 'genealabs/laravel-caffeine/drip',
];

**Comment by mikebronner** [comment]
Thanks! :) One more question: what does the following output:

```sh
php artisan tinker
return url('/');
```

**Comment by Kyosfonica** [comment]
artisan crashes

vagrant@homestead:~/Code/salunet$ php artisan tinker
PHP Catchable fatal error:  Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 62 and defined in /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 103
PHP Stack trace:
PHP   1. {main}() /home/vagrant/Code/salunet/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/vagrant/Code/salunet/artisan:36
PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:105
PHP   4. Illuminate\Foundation\Application->bootstrapWith() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:219
PHP   5. Illuminate\Foundation\Bootstrap\LoadConfiguration->bootstrap() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:203
PHP   6. Illuminate\Foundation\Bootstrap\LoadConfiguration->loadConfigurationFiles() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:38
PHP   7. require() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:60
PHP   8. url() /home/vagrant/Code/salunet/config/genealabs-laravel-caffeine.php:5
PHP   9. app() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:736
PHP  10. Illuminate\Foundation\Application->make() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:105
PHP  11. Illuminate\Container\Container->make() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
PHP  12. Illuminate\Container\Container->build() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
PHP  13. Illuminate\Container\Container->Illuminate\Container\{closure}() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
PHP  14. Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Container/Container.php:289
PHP  15. Illuminate\Routing\UrlGenerator->__construct() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php:62

Catchable fatal error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 62 and defined in /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 103

Call Stack:
    0.0004     225488   1. {main}() /home/vagrant/Code/salunet/artisan:0
    0.1496    2493728   2. Illuminate\Foundation\Console\Kernel->handle() /home/vagrant/Code/salunet/artisan:36
    0.1496    2493856   3. Illuminate\Foundation\Console\Kernel->bootstrap() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:105
    0.1496    2494024   4. Illuminate\Foundation\Application->bootstrapWith() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:219
    0.1630    2627080   5. Illuminate\Foundation\Bootstrap\LoadConfiguration->bootstrap() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:203
    0.1678    2656000   6. Illuminate\Foundation\Bootstrap\LoadConfiguration->loadConfigurationFiles() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:38
    0.2578    3117384   7. require('/home/vagrant/Code/salunet/config/genealabs-laravel-caffeine.php') /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php:60
    0.2578    3117792   8. url() /home/vagrant/Code/salunet/config/genealabs-laravel-caffeine.php:5
    0.2578    3118048   9. app() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:736
    0.2578    3118232  10. Illuminate\Foundation\Application->make() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:105
    0.2578    3118232  11. Illuminate\Container\Container->make() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:697
    0.2579    3118312  12. Illuminate\Container\Container->build() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Container/Container.php:629
    0.2579    3118344  13. Illuminate\Container\Container->Illuminate\Container\{closure}() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Container/Container.php:731
    0.2579    3118512  14. Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Container/Container.php:289
    0.2750    3525648  15. Illuminate\Routing\UrlGenerator->__construct() /home/vagrant/Code/salunet/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php:62

**Comment by mikebronner** [comment]
Egads ... should have expected that, sorry. What is the APP_URL environment variable set to in your `.env` file?

**Comment by Kyosfonica** [comment]
APP_URL=http://localhost

If I comment out the service provider it crashes.
If I comment out the published config file it works.

vagrant@homestead:~/Code/salunet$ php artisan tinker
Psy Shell v0.7.2 (PHP 5.6.13-1+deb.sury.org~trusty+3 — cli) by Justin Hileman
>>> return url('/')
=> "http://localhost"

**Comment by mikebronner** [comment]
Thanks for the report, I will look into this weekend. If you happen to come across a fix, please let me know and I will fix it ASAP. :) My initial hunch is that it's a configuration problem, and not necessarily an issue with the package itself, but I'll have to reproduce the issue first.

**Comment by Kyosfonica** [comment]
It seems that in config files you are not supposed to use framework helpers.
https://github.com/laravel/framework/issues/7671

**Comment by mikebronner** [comment]
Thanks! I updated the readme, and released a new version for L5.3 (0.4.0), can you give it a shot and see how it works? You will need to republish the config file. (If you aren't making any changes to config, I would recommend not publishing it.) -- Closing for now, but if the issue persists, please re-open. Thanks! :)
