### ISSUE TITLE
Laravel 5.3 Not Compatible

### ISSUE THREAD

**Issue by bfblackjack** [GeneaLabs/laravel-caffeine#41]
Upon installing laravel caffeine, laravel fails to find the package/service provider.

Composer.json has the correct entry -- "genealabs/laravel-caffeine": "^0.4.1"

Application service provider in config/app has been added - GeneaLabs\LaravelCaffeine\LaravelCaffeineServiceProvider::class,

Yet artisan throws the following error..

 [Symfony\Component\Debug\Exception\FatalThrowableError]
 Class 'GeneaLabs\LaravelCaffeine\LaravelCaffeineServiceProvider' not found

**Comment by mikebronner** [comment]
The issue is the service provider. It has been renamed (I'm guessing you're upgrading from a previous version?):

```php
GeneaLabs\LaravelCaffeine\providers\LaravelCaffeineService::class,
```

**Comment by bfblackjack** [comment]
@mikebronner Thanks for the quick reply. Looks like it works now! The readme still lists the previous service provider so I was unaware that was changed. Thanks!

**Comment by mikebronner** [comment]
Oi!! Thanks for catching that ... I thought I fixed it, doing that now.
