### ISSUE TITLE
Ignore L5.3 Logout Form

### ISSUE THREAD

**Issue by mikebronner** [GeneaLabs/laravel-caffeine#43]
Laravel 5.3 changed its logout route to be a post, and uses a form in the menu to do so. This has the unintended consequence of keeping the session alive indefinitely, something we don't want.

I would like to explore options to not keep the session alive, yet remain user-friendly. Not sure how feasable this is:
- Do not keep session alive if only the logout form and no other form is rendered.

**Comment by bbashy** [comment]
Since most projects have the meta tag for csrf-token on every page, that's the same issue?

**Comment by mikebronner** [comment]
Yea, it is ... :(

**Comment by lostlian** [comment]
The issue would have refreshing the page every x minutes acording to the configuration file right?

**Comment by mikebronner** [comment]
@lostlian no, the page itself does not refresh, but sends and AJAX request in the background. Essentially the issue is that if you have the logout form in the menu, its equivalent to having a session that never expires, and that is not good. I am still contemplating on a path forward that makes sense for this project.

**Comment by mikebronner** [comment]
Will be addressed when looking at #45
