### ISSUE TITLE
Problems with the installation

### ISSUE THREAD

**Issue by patpaskoch** [GeneaLabs/laravel-caffeine#44]
working with laravel 5.2.45

installed via `composer require genealabs/laravel-caffeine:~0.3.11`

inserted in the config/app file 

`GeneaLabs\LaravelCaffeine\Providers\LaravelCaffeineService::class,`

but laravel throws 

> Class 'GeneaLabs\LaravelCaffeine\Providers\LaravelCaffeineService' not found 

error.

g patrick

**Comment by patpaskoch** [comment]
I got it working by replaceing

'GeneaLabs\LaravelCaffeine\Providers\LaravelCaffeineService' 

with

`GeneaLabs\LaravelCaffeine\LaravelCaffeineServiceProvider::class`

no it also shows the  route in the php artisan route:list

**Comment by mikebronner** [comment]
Ah yes, the new version doesn't support 5.2. I will update the documentation to be more explicit and direct you to the proper documentation for that version. Thanks for reporting this. :)

**Comment by patpaskoch** [comment]
so 5.2.* versions are not supported also not with 

`genealabs/laravel-caffeine:~0.3.11` ?

**Comment by mikebronner** [comment]
Version 0.3.12 supports Laravel 5.2, while version 0.4.x is for Laravel 5.1 (LTS) and 5.3 (current). The README shows documentation for the latest version, and hence the instructions for adding the provider in `config/app.php` weren't the correct ones for your version. :)

**Comment by patpaskoch** [comment]
ah ok so if I made the adjustments in `config/app.php`, and I see the genealabs route in my route:list it should work fine.

thanks for the support and the whole project.

**Comment by mikebronner** [comment]
I think so. Double check back when I have the correct README for version 0.3.x in place, just to make sure. :) Should be within the next few days.

**Comment by patpaskoch** [comment]
ok

**Comment by marcelgruber** [comment]
Looking forward to this. Thanks.

**Comment by mikebronner** [comment]
This should now be updated on the master README of the repo (added link to 5.2 instructions). Thanks for your patience. :)

**Comment by marcelgruber** [comment]
Hmm, interesting; it still seems to not work for 5.2. I will let you know what I find.

**Comment by mikebronner** [comment]
@marcelgruber can you provide any error messages, etc? What's not working specifically?

**Comment by marcelgruber** [comment]
@mikebronner I followed the three steps, but the server is throwing a 500. Nothing seems to be added to my routes file after following the steps, though, so that could be the problem. Does there need to be a route added?
Cheers

**Comment by mikebronner** [comment]
If you're getting a 500 error, try and follow it back to the root cause by checking your laravel log file and debugging. It may be something completely unrelated or a configuration issue.

Double-check the following as well:
1 you have added the following provider entry in `/config/app.php`:
```php
GeneaLabs\LaravelCaffeine\LaravelCaffeineServiceProvider::class,
```
2. Check your composer.lock file to make sure the version installed is `0.3.12`. If not, delete the vendor directory, fix the composer.json entry accordingly, and run `composer update` again.
3. Leave the middleware out for now.
4. Test if you still get the 500 error. If not, go ahead and add the middleware registration:
```php
   protected $middleware = [
       // other entries above
       \GeneaLabs\LaravelCaffeine\Http\Middleware\LaravelCaffeineDripMiddleware::class,
   ];
```

**Comment by marcelgruber** [comment]
Will do. I'll be sure to let you know if I find anything that could contribute here.

**Comment by marcelgruber** [comment]
`composer update` seems to have fixed the issue. Thanks so much!

**Comment by mikebronner** [comment]
Great news :-)

**Comment by marcelgruber** [comment]
PS, I did manage to find something worth contributing.

If one publishes the config file via the command

`php artisan vendor:publish --tag=genealabs-laravel-caffeine`

And then attempts to do any composer commands

> php artisan clear-compiled
PHP Catchable fatal error:  Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /var/www/html/project/bootstrap/cache/compiled.php on line 5238 and defined in /var/www/html/project/bootstrap/cache/compiled.php on line 9411
Script php artisan clear-compiled handling the post-install-cmd event returned with an error

                                                                               
  [RuntimeException]                                                             
  Error Output: PHP Catchable fatal error:  Argument 2 passed to Illuminate\Rou  
  ting\UrlGenerator::__construct() must be an instance of Illuminate\Http\Reque  
  st, null given, called in /var/www/html/project/bootstrap/cache/compiled  
  .php on line 5238 and defined in /var/www/html/project/bootstrap/cache/c  
  ompiled.php on line 9411  


It works fine though as long as the config file does not get published

**Comment by felorodri** [comment]
@marcelgruber Reading your last error after you publish your config file... seems like you kept the url() helper in the domain key of the config array. Can you confirm this?

**Comment by mikebronner** [comment]
@felorodri thanks for jumping in and helping out with the solution. :)

**Comment by marcelgruber** [comment]
@felorodri You are correct in saying that the url('') line is in there which could be problematic. This is the exact code that gets initially published:

<?php

return [
    'dripIntervalInMilliSeconds' => 300000,
    'domain' => url('/'),
    'route' => 'genealabs/laravel-caffeine/drip',
];

If I change the `url('/')` code to `'/'`, there are no issues.

**Comment by fredabel** [comment]
Hi everyone thanks for this package but I need to remove it but this what happens
![screen shot 2017-10-28 at 10 51 20 am](https://user-images.githubusercontent.com/31060728/32131025-a5e6b024-bbd6-11e7-826a-13376b8240f3.png)
I'm using laravel 5.4

**Comment by mikebronner** [comment]
@fredabel please open a new issue for this so we can track this. thanks :)

**Comment by mohannad1995** [comment]
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ResourceRegistrar.php line 360:

  Object of class Closure could not be converted to string


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
I'm using laravel 5.6
