### ISSUE TITLE
laravel-caffeine injecting itself into Groove Widget script

### ISSUE THREAD

**Issue by ApeWare** [GeneaLabs/laravel-caffeine#46]
I am trying to install the [Groove](https://www.groovehq.com/) Widget code into my project but part of the code for laravel-caffeine seems to be injected into the Groove widget code. It looks like the Groove widget creates an iFrame with a body tag and I am not sure if l-c is detecting this additional body tag and injecting code into it, breaking the widget.

Here is sample code for the GrooveHQ Widget as it is in my project

``` html
<!-- BEGIN GROOVE WIDGET CODE -->
<script id="grv-widget">
  /*<![CDATA[*/
  window.groove = window.groove || {}; groove.widget = function(){ groove._widgetQueue.push(Array.prototype.slice.call(arguments)); }; groove._widgetQueue = [];
  groove.widget('setWidgetId', 'xxxxxxxxxxxxxx');
  !function(g,r,v){var a,c,n=r.createElement("iframe");(n.frameElement||n).style.cssText="width: 0; height: 0; border: 0",n.title="",n.role="presentation",n.src="javascript:false",r.body.appendChild(n);try{a=n.contentWindow.document}catch(b){c=r.domain;var d="javascript:document.write('<head><script>document.domain=\""+c+"\";</",i="script></head><body></body>')";n.src=d+i,a=n.contentWindow.document}var s="https:"==r.location.protocol?"https://":"http://",p="http://groove-widget-production.s3.amazonaws.com".replace("http://",s);n.className="grv-widget-tag",a.open()._l=function(){c&&(this.domain=c);var t=this.createElement("script");t.type="text/javascript",t.charset="utf-8",t.async=!0,t.src=p+"/loader.js",this.body.appendChild(t)},a.write('<body onload="document._l();">'),a.close()}(window,document);
  /*]]>*/
</script>
<!-- END GROOVE WIDGET CODE -->
```

Here is how it renders after laravel-caffeine injects itself into the widget code

``` html
<script id="grv-widget">
    /*<![CDATA[*/
    window.groove = window.groove || {}; groove.widget = function(){ groove._widgetQueue.push(Array.prototype.slice.call(arguments)); }; groove._widgetQueue = [];
    groove.widget('setWidgetId', 'xxxxxxxxxxxxxx');
    !function(g,r,v){var a,c,n=r.createElement("iframe");(n.frameElement||n).style.cssText="width: 0; height: 0; border: 0",n.title="",n.role="presentation",n.src="javascript:false",r.body.appendChild(n);try{a=n.contentWindow.document}catch(b){c=r.domain;var d="javascript:document.write('<head><script>document.domain=\""+c+"\";</",i="script></head><body><script>setInterval(function(){var e=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject('Microsoft.XMLHTTP');e.open('GET','http://v3.dev/genealabs/laravel-caffeine/drip',!0);e.setRequestHeader('X-Requested-With','XMLHttpRequest');e.send();}, 300000);</script>
')";n.src=d+i,a=n.contentWindow.document}var s="https:"==r.location.protocol?"https://":"http://",p="http://groove-widget-production.s3.amazonaws.com".replace("http://",s);n.className="grv-widget-tag",a.open()._l=function(){c&&(this.domain=c);var t=this.createElement("script");t.type="text/javascript",t.charset="utf-8",t.async=!0,t.src=p+"/loader.js",this.body.appendChild(t)},a.write(''),a.close()}(window,document);
    /*]]>*/
<!-- END GROOVE WIDGET CODE -->
```

I was wondering if there are any solutions or workarounds to get them playing well together.

**Comment by mikebronner** [comment]
Hi @ApeWare, thanks for reporting this! The next version will be one where you explicitly decide what forms Caffeine for Laravel should work on. This should address this, and some other issues. Unfortunately it takes us away from automagically working, but with Laravel now having the default logout route via POST (requiring a form on the front-end), and similar conflicts with other packages like you are seeing, it might be better to add a tag to a form to indicate it to stay alive.

Would this solution be one that you would welcome?

**Comment by ApeWare** [comment]
I like the automagically working aspect, as we have several forms and it currently "just works". If there were an option to "ignore specific forms" - for my specific case and maybe others who are running into conflicts like this - may be a preferred solution.

Either way I appreciate the response and consideration.

**Comment by chrisbaswell** [comment]
Ran into this issue myself today.  Any ideas when if it will be addressed soon?  We really would like to keep using this package b/c it just works.

**Comment by mikebronner** [comment]
Closing for now, since this is quite old and some updates have been released in the mean time. Please open new issue if this is persisting.

**Comment by ApeWare** [comment]
We switched from Groove so I can no longer confirm if the issue persists. Thanks.

**Comment by mikebronner** [comment]
Thanks for the update. :)
