### ISSUE TITLE
Default 'genealabs/laravel-caffeine/drip' route doesn't work

### ISSUE THREAD

**Issue by ivansammartino** [GeneaLabs/laravel-caffeine#47]
Hello,
I installed Caffeine 0.4.1 on Laravel 5.3: to test, I setup session.lifetime = 1 (minute) and dripIntervalInMilliSeconds = 30000 (30 seconds); so, after one or more minute, I should be able to work on my form 'cause of Caffeine

Instead, I get a ```TokenMismatchException```
Giving some try, I changed Caffeine route parameter to a known one (i.e. '/') and wow, I don't get the ```TokenMismatchException``` anymore

Reverting to default Caffeine route and looking at my route list (```php artisan route:list```) I see the ```genealabs/laravel-caffeine/drip``` one, but It's not under the ```web``` middleware: I suspect that this is the problem, am I right? Any fix, please?

Thanks

**Comment by mikebronner** [comment]
Hi @ivanhalen, I'm sorry you're having issues with this. Is this an upgraded project, or a brand new L5.3 project? I will investigate as well this weekend to see if something changed.

**Comment by ivanhalen** [comment]
Thanks for reply, it's a brand new L5.3 project

**Comment by Jono20201** [comment]
Also having this same issue. Route is also not going under web middleware.

**Comment by mikebronner** [comment]
@Jono20201 Thanks for letting me know ... sorry for the delay on this.

**Comment by Jono20201** [comment]
@mikebronner No worries. Im working on a possible PR to allow you to configure middleware via config options. Would this be something you would consider merging?

**Comment by Jono20201** [comment]
@mikebronner See: https://github.com/GeneaLabs/laravel-caffeine/pull/49

**Comment by mikebronner** [comment]
Closing, as old issue. Please resubmit it still occurring.
