### ISSUE TITLE
How to know if Caffeine is working?

### ISSUE THREAD

**Issue by mesqueeb** [GeneaLabs/laravel-caffeine#48]
I just installed Caffeine on Laravel 5.2.
How can I verify if I did everything correctly and it's working?
Cheers!

**Comment by mikebronner** [comment]
There's not really much to notice. Open your browser development inspector, watch the drip request, make sure they don't error out. Leave your browser open on a page with a form, walk away for two hours, come back and check to see if you can still submit the form.

**Comment by mesqueeb** [comment]
Dear Mike!
It doesn't seem to work. Maybe I installed it incorrectly, but I went over each step and double checked.
Any advice how to error check?

**Comment by mikebronner** [comment]
Hi @mesqueeb, sorry for the troubles you are experiencing. I will double-check on a fresh L5.3 install later today and report back.

**Comment by mesqueeb** [comment]
Hey Mike, I use 5.2!!

**Comment by mikebronner** [comment]
@mesqueeb what was the issue (please share, might help others)?

**Comment by mesqueeb** [comment]
Hey I followed these 3 steps here:
https://github.com/GeneaLabs/laravel-caffeine/tree/166e2ca08af7cc62a59360f33e03d1cb8478df6a

But my page doesnt get dripped.

1) Do i need to do "composer install" after require? 

I have an inline token in my html's header.
2) Does the way this token is configured into the html matter for caffeine?

**Comment by mikebronner** [comment]
Oh, sorry, misunderstood, thought you got it working. L5.2 is not supported. I only support LTS and current (5.3).

**Comment by zippos** [comment]
Not related, but in app providers

GeneaLabs\LaravelCaffeine\Providers\LaravelCaffeineService::class,

should be changed to

GeneaLabs\LaravelCaffeine\LaravelCaffeineServiceProvider::class,

**Comment by mikebronner** [comment]
@zippos That is only true for Laravel 5.2. For Laravel 5.1 and 5.3 the former format is the correct one.

**Comment by zippos** [comment]
I'm using the latest version 5.3 and I had to use:

GeneaLabs\LaravelCaffeine\LaravelCaffeineServiceProvider::class,

Also I've needed to add the middleware.

Also the config file should not use url() function because it 5.3 the config files are loaded way earlier and that will cause an error. So instead of that you can use env('APP_URL')

**Comment by mikebronner** [comment]
@zippos It sounds to me like you might not be using the most recent version. None of the steps you described above should be necessary. Please make sure you have version 0.4.1. Can you let me know which version you have installed so I can double-check? Thanks!

**Comment by zippos** [comment]
That's true, my bad. I just pulled a few hours ago but since on this machine I'm using PHP 5.6, I got an earlier version due to stability reasons.

Sorry again. :)

**Comment by mikebronner** [comment]
@zippos No worries, glad you got it sorted. :) Yea, there is a PHP dependency of the latest version 0.4.x to have PHP 7.0 or greater, that's probably what told the installer to use the older version.

@mesqueeb Have you been able to get it running?

**Comment by uxm** [comment]
When using 
``composer require genealabs/laravel-caffeine,``

Version 0.3.12 is being installed. I am on Laravel version 5.3.22.

After reading the info above, I went and upgraded my localhost from PHP 5.6.15 to PHP 7.1. However, version 0.3.12 is still being installed. Am I missing something here?

**Comment by uxm** [comment]
Just to update - I did solve this issue and got 0.4 installed. For some reason PHP 7 was showing in WAMP but was actually using 5.6. I couldn't get having both versions available working after a couple hours of work so I just went completely to PHP 7.

**Comment by jannejava** [comment]
I am on PHP7, Laravel 5.3.29 and I still get Version 0.3.12 when doing composer require. Have I missed something?

**Comment by mikebronner** [comment]
Closing. Please open new issue if persists.
