### ISSUE TITLE
Correct namespace to Caffine in readme for Laravel 5.3?

### ISSUE THREAD

**Issue by jannejava** [GeneaLabs/laravel-caffeine#50]
# Issue
I get "Class 'GeneaLabs\LaravelCaffeine\Providers\LaravelCaffeineService' not found" if I follow the installation instructions on the front page.

Found an old github issue regarding problems with Laravel 5.2 and changed to GeneaLabs\LaravelCaffeine\LaravelCaffeineServiceProvider::class and I get passed the installation. Which one is the correct one for Laravel 5.3, or will there be any problems?

## Environment
Laravel Version: 5.3.29
Laravel Caffeine Package Version: 0.3.12
PHP Version: 7.1

**Comment by chuckienorton** [comment]
Thew newest version should be: 

`GeneaLabs\LaravelCaffeine\LaravelCaffeineServiceProvider::class`

Can creator update the docs?

**Comment by mikebronner** [comment]
You should be updating to package 0.4.x when using Laravel 5.3+.
