### ISSUE TITLE
Error code 255 in composer

### ISSUE THREAD

**Issue by goranata** [GeneaLabs/laravel-caffeine#52]
Hi, 

Upon submiting vendor:publish as proposed, in the manual, I get a composer error code 255, on fresh new install on Laravel 5.2.

Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize
Script php artisan optimize handling the post-install-cmd event returned with error code 255.

Please advice,

**Comment by mikebronner** [comment]
Hi @goranata, which version of larval-caffeine are you trying to install? The latest version is not compatible with L5.2.

**Comment by goranata** [comment]
Hi @mikebronner,

Thanks for the reply.
 
I've tried everything as mentioned in the instructions.
After realizing the 5.2 compatibility issues, I've switched the whole project on 5.1. After vendor publishing, did the same as in 5.2. 
I've also realized, that, upon switching to version 2, it installed version 3.12.

**Comment by mikebronner** [comment]
Can you post a screenshot of the console output?

**Comment by mikebronner** [comment]
Closing. Please re-open if issue persists.

**Comment by arm092** [comment]
If this happened after Laravel update from 6.x to 7.x, then this could be due to the update of Symfony. See the upgrade guide of this part: https://laravel.com/docs/7.x/upgrade#symfony-5-related-upgrades
