### ISSUE TITLE
Having drip interval relative to session ?

### ISSUE THREAD

**Issue by thesupad** [GeneaLabs/laravel-caffeine#54]
Hi,

Not an issue but a suggestion : what about setting by default the drip interval in relation of the session time configured ?

Maybe config("session.lifetime")*60*1000/2 on line 27 in the MiddleWare ?

**Comment by mikebronner** [comment]
Thanks :) Will think on this.

**Comment by ItaloBC** [comment]
Why would you use a drip interval in relation to the session time? I don't see any kind of advantage doing this.

**Comment by mikebronner** [comment]
Checking for when to reload the page is always dependent on session timeout. We should not be reloading the page arbitrarily if the session is not about to expire. The drip interval itself is not dependent on the session.

**Comment by mikebronner** [comment]
@ItaloBC Sorry, mixed up the threads we are on. (As per the PR the threshold is relative to the session.)

At this point I do not think that it is necessary to make the drip relative to the session. The developer should be able to adjust this to their needs. Closing this for now. Thanks @thesupad for the suggestion, though!

**Comment by ItaloBC** [comment]
lol I was ready to rant. jk,
