### ISSUE TITLE
Still Getting TokenMismatchException after laravel session lifetime even after 0.3.11 caffeine version.

### ISSUE THREAD

**Issue by lfsaestrella** [GeneaLabs/laravel-caffeine#57]
The error isn't gone yet. I replaced the url('\') as you requested and this is what happened: The network tab from chrome returned a 404 error from the drip, instead of the usual 204. The replacement fixed the artisan problem, but now it can't find the drip route. Also, the original issue had not been solved, as the TokenMismatchException continues to be thrown.

**Comment by mikebronner** [comment]
I need more to go on here. It sounds like there is a configuration issue. Can you remove the caffeine configuration file you published? Are you customizing anything in the configuration file?

**Comment by lfsaestrella** [comment]
If I remove the configuration file, the drips interval goes back to the 5 minutes default. Then, I have to reconfigure the session interval to 6 minutes for testing. The TokenMismatchException is still thrown if I submit the login form after 6 minutes. I can see the drip being fired in the chrome network tab after 5 minutes, and it always has the expected 204 response. Although there are no errors, it seems that laravel doesn't recognize the drip as a "session reload". I did a little test: I loaded the login page and waited for 5 minutes. Then I reloaded the page and tried to send the form 2 minutes later. That's 7 ellapsed minutes, and if I hadn't reloaded the page, the session would had expired in 6. Well, I successfully submited the form even after 7 minutes, so the page reloading made the laravel session expires 6 minutes after the reload.
It's odd that it doesn't recognize the drips as a way of keeping the session alive for another 6 minutes. The drip is fired, it has no errors, I receive the 204 response, and even though the session expires after the configured interval (6 minutes, in this case) after the page loading. Below there are my Kernel.php and my config/app.php. My routes aren't under a group.

By the way, I tested it in a login form normally submitted, without ajax. If I load a modal with a form inside, your middleware does not work, since your middleware adds the script into the loaded content's body, replacing the `</body>` with the `<script>...</script></body>`. I modified the middleware to allow it to fire drips in every loaded content. All the tests were realized with the original middleware, though.

Kernel.php:

    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \GeneaLabs\LaravelCaffeine\Http\Middleware\LaravelCaffeineDripMiddleware::class,
    ];
    
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \App\Http\Middleware\VerifyLanguage::class,
            
        ],

        'api' => [
            'throttle:60,1',
        ],
    ];


app.php:

       'providers' => [

       
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        GeneaLabs\LaravelCaffeine\LaravelCaffeineServiceProvider::class,
        //'Maatwebsite\Excel\ExcelServiceProvider',
        

        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

    ],

**Comment by Jono20201** [comment]
If you run `php artisan route:list --path=caffeine-drip` do you see anything listed under the middleware column? If so, what?

**Comment by lfsaestrella** [comment]
An update: ivanvermeyen first solution on issue #22 worked. That is, creating my own route `Route::get('genealabs/laravel-caffeine/drip', ['uses' => 'PagesController@drip']);` and controller with drip method:

    public function drip()
    {
        return response('', 204);
    }

Answering @Jono20201: I think you meant to run 
`php artisan route:list --path=caffeine/drip`
Is that it? Because the one you posted returned nothing. When I run this command, I receive the following answer:

Domain: none
Method: GET|HEAD
URI: genealabs/laravel-caffeine/drip
Name: none
Action: GeneaLabs\LaravelCaffeine\Http\Controllers\LaravelCaffeineController@drip
Middleware: none

I also tested it putting the middleware in the web group in Kernel.php, but it doesn't work as well.

Certainly the problem has something to do with the routes, as the above solution by ivanvermeyen worked.
By the way: My modification that allows the script to fire in forms loaded in contents that do not have the `<body></body>` tag inside them worked, along with my own route and controller.

**Comment by Jono20201** [comment]
You're correct, I must have modified the URL on my app.

I think this is the same issue as I was having, where it wasn't picking up the web middle ware. Unless this is set on the route it will not work as it cannot mofidy sessions.

I fixed this using a custom middleware option, currently a PR: #49

**Comment by lfsaestrella** [comment]
Yes, I thought it could be some route misconfiguration, but I couldn't make it work even when I put the middleware inside the "web" group in Kernel.php. I also put the routes explicitly inside the web group and the result is the same.

**Comment by mikebronner** [comment]
hi @Jono20201 and @lfsaestrella, thanks for looking into this some more. I will ponder on this... am considering various options on how to move forward, especially now with the L5.3 move to having logout button be a form.

**Comment by mikebronner** [comment]
Closing ... will handle this as part of #43 .
