### ISSUE TITLE
syntax errors in LaravelCaffeineService.php

### ISSUE THREAD

**Issue by Bulmer** [GeneaLabs/laravel-caffeine#58]
## Actual Behavior
I have just installed laravel-caffeine and there seems to be multiple syntax errors on lines 28, 33 and 38.

## Environment
- PHP Version: 7.0
- Laravel Version: 5.4
- LaravelCaffeine Version:latest

**Comment by Jono20201** [comment]
Of which file(s)? With what error(s)?

**Comment by Bulmer** [comment]
LaravelCaffeineService.php
The first one:
FatalErrorException in LaravelCaffeineService.php line 28:
syntax error, unexpected ':', expecting ';' or '{'

**Comment by Jono20201** [comment]
@Bulmer Your still running PHP 5.6 then. Its possible that your CLI PHP is 7.0 but your webserver PHP is not.

**Comment by Bulmer** [comment]
Ok, false alarm. My PHP version jumped back to 5.6 at a recent reboot (im running both versions locally).
