### ISSUE TITLE
Can't get it intalled in Laravel 5.2

### ISSUE THREAD

**Issue by marwan2** [GeneaLabs/laravel-caffeine#60]
After installation and add its Service Provider to my config/app.php
`GeneaLabs\LaravelCaffeine\Providers\LaravelCaffeineService::class,`

An error displayed: 
`FatalErrorException in ProviderRepository.php line 146:
Class 'GeneaLabs\LaravelCaffeine\Providers\LaravelCaffeineServiceProvider' not found`

**Comment by mikebronner** [comment]
Are you sure you followed the directions here: https://github.com/GeneaLabs/laravel-caffeine/tree/166e2ca08af7cc62a59360f33e03d1cb8478df6a? (The default readme does not apply to L5.2).

**Comment by marwan2** [comment]
Yes, I followed 5.2 docs,
I'll try to install it in a new clean project, and feed back you

**Comment by mikebronner** [comment]
Sounds good, let me know how it goes. Unfortunately I won't be able to make any changes retro-active to 5.2 at this point.

**Comment by mikebronner** [comment]
Closing as issue is stale, and on old version of Laravel.
