### ISSUE TITLE
Does it Work for L5.4?

### ISSUE THREAD

**Issue by lostlian** [GeneaLabs/laravel-caffeine#63]
## Environment
- PHP Version: 7
- Laravel Version: 5.4
- LaravelCaffeine Version: 0.3.12

## Question
I just installed for a 5.4 laravel instalation running on forge. It doenst trace any errors. i dont know if it works yet. I openen a form and have being waiting for over 2 hours and it looks it works. But have you test it out? so i can push it to production?

**Comment by mikebronner** [comment]
Yes, I have it installed on L5.4 systems and testing has shown it to work. Please let me know if you encounter any issues, I will try to respond as quickly as I can. Thanks for using Caffeine! :)
