### ISSUE TITLE
Interface 'App\Jobs\SelfHandling' not found

### ISSUE THREAD

**Issue by developerMerna** [GeneaLabs/laravel-caffeine#65]
Interface 'App\Jobs\SelfHandling' not found this error appear when we update laravel version from 5.1 to 5.4

**Comment by mikebronner** [comment]
Hi @developerMerna thanks for reporting this. Can you please provide the entire stack trace of the error?

**Comment by mikebronner** [comment]
Closing ... App\Jobs\SelfHandling is not part of this package's code-base.
