### ISSUE TITLE
Support for laravel 5.5

### ISSUE THREAD

**Issue by migas5000** [GeneaLabs/laravel-caffeine#67]
## Acutal Behavior
genealabs/laravel-caffeine 0.4.2 requires illuminate/support 5.1.* || 5.3.* || 5.4.* -> satisfiable by laravel/framework[v5.4.36], illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
## Environment
- PHP Version: 
- Laravel Version: 
- LaravelCaffeine Version:

**Comment by mikebronner** [comment]
You need to update the package version in your composer.json to the version that is compatible with L5.5.
