### ISSUE TITLE
Breaking PHPUnit's assertViewIs()

### ISSUE THREAD

**Issue by agjino** [GeneaLabs/laravel-caffeine#82]
## Expected Behavior

In PHPUnit:

$response = $this->get('/testpage');
$response->assertViewIs('layouts.testpage');

Should return true.

## Acutal Behavior

Test fails with feedback: The response is not a view.

## Environment
- PHP Version: 7.1
- Laravel Version: 5.5
- LaravelCaffeine Version: 0.6.5 (latest as of this post)

## Manual fix
Removed Caffeine during tests from all pages using the header:
@if (config('app.env') === 'testing'')
    <meta name="caffeinated" content="false">
@endif

In phpunit.xml the following setup must exist:

```
<php>
        <env name="APP_ENV" value="testing"/>
```
.....

**Comment by mikebronner** [comment]
Thanks, will take a look. May take some time, I'm currently swamped with other things. :)
