### ISSUE TITLE
composer require error

### ISSUE THREAD

**Issue by XavRsl** [GeneaLabs/laravel-caffeine#84]
## Expected Behavior
I'm expecting the package to be installed.

## Actual Behavior
Installation failed.

## Environment
- PHP Version: 7.1.11
- Laravel Version: 5.5.34
- LaravelCaffeine Version: none

## Stack Trace
$ composer require genealabs/laravel-caffeine

Using version ^0.6.7 for genealabs/laravel-caffeine
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for genealabs/laravel-caffeine ^0.6.7 -> satisfiable by genealabs/laravel-caffeine[0.6.7].
    - Conclusion: remove laravel/framework v5.5.34
    - Conclusion: don't install laravel/framework v5.5.34
    - genealabs/laravel-caffeine 0.6.7 requires illuminate/routing 5.6.* -> satisfiable by laravel/framework[5.6.x-dev], illuminate/routing[5.6.x-dev, v5.6.0, v5.6.1, v5.6.2, v5.6.3].
    - Can only install one of: laravel/framework[5.6.x-dev, v5.5.34].
    - don't install illuminate/routing 5.6.x-dev|don't install laravel/framework v5.5.34
    - don't install illuminate/routing v5.6.0|don't install laravel/framework v5.5.34
    - don't install illuminate/routing v5.6.1|don't install laravel/framework v5.5.34
    - don't install illuminate/routing v5.6.2|don't install laravel/framework v5.5.34
    - don't install illuminate/routing v5.6.3|don't install laravel/framework v5.5.34
    - Installation request for laravel/framework (locked at v5.5.34, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.34].

Thanks for your help!

**Comment by mikebronner** [comment]
@XavRsl Thanks for reporting this! I just released a fix, should work now in release 0.6.8. Please let me know if you still have problems. :)

**Comment by XavRsl** [comment]
Yep, problem solved.

Thanks!

**Comment by mikebronner** [comment]
@XavRsl Awesome :)

**Comment by RoshanJafri** [comment]
@mikebronner Hey, I am facing this error again>
Problem 1
    - Installation request for genealabs/laravel-caffeine ^8.0 -> satisfiable by genealabs/laravel-caffeine[8.0.0].    
    - Conclusion: remove laravel/framework v7.29.2
    - Conclusion: don't install laravel/framework v7.29.2
    - genealabs/laravel-caffeine 8.0.0 requires illuminate/routing ^8.0 -> satisfiable by illuminate/routing[8.x-dev, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4, v8.1.0, v8.10.0, v8.11.0, v8.11.1, v8.11.2, v8.12.0, v8.12.1, v8.12.2, v8.12.3, 
v8.13.0, v8.14.0, v8.15.0, v8.16.0, v8.16.1, v8.17.0, v8.17.2, v8.18.0, v8.18.1, v8.19.0, v8.2.0, v8.20.0, v8.20.1, v8.21.0, v8.22.0, v8.22.1, v8.23.1, v8.24.0, v8.25.0, v8.26.0, v8.26.1, v8.27.0, v8.28.0, v8.28.1, v8.29.0, v8.3.0, v8.30.0, v8.30.1, v8.31.0, v8.32.0, v8.32.1, v8.33.0, v8.33.1, v8.34.0, v8.35.0, v8.35.1, v8.36.0, v8.36.1, v8.36.2, v8.37.0, v8.4.0, v8.5.0, v8.6.0, v8.7.0, v8.7.1, v8.8.0, v8.9.0].
    - don't install illuminate/routing 8.x-dev|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.0.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.0.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.0.2|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.0.3|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.0.4|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.1.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.10.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.11.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.11.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.11.2|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.12.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.12.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.12.2|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.12.3|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.13.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.14.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.15.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.16.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.16.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.17.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.17.2|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.18.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.18.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.19.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.2.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.20.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.20.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.21.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.22.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.22.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.23.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.24.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.25.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.26.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.26.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.27.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.28.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.28.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.29.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.3.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.30.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.30.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.31.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.32.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.32.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.33.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.33.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.34.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.35.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.35.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.36.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.36.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.36.2|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.37.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.4.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.5.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.6.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.7.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.7.1|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.8.0|don't install laravel/framework v7.29.2
    - don't install illuminate/routing v8.9.0|don't install laravel/framework v7.29.2
    - Installation request for laravel/framework (locked at v7.29.2, required as ^7.0) -> satisfiable by laravel/framework[v7.29.2]
