### ISSUE TITLE
Forms still expire

### ISSUE THREAD

**Issue by ItaloBC** [GeneaLabs/laravel-caffeine#89]
## Expected Behavior

Forms stills alive

## Actual Behavior

They expire

## Details

Using the middleware method, all the drips get 204, no problem so far. The only thing I noted is that after the session time expiration, the XSRF-TOKEN cookie being sent for the drip disappears.

It seems that Laravel doesn't want to maintain the token session alive in the form even if the drips are correctly sent and responded.

Already removed and reinstalled Caffeine and dumped the autoload juts to be sure.

## Workaround

~~Using Axios, I made a normal get to the form located `axios.get('https://myapp.test/login` and the token lives throught the timeout . But using axios to the default dripping route doesn't.~~

~~It would seem that Laravel session enforces the current URL, but after using get on other routes of the application (like `axios.get('https://myapp.test/artist/michael-jackson/albums/all')`) also keep them alive.~~

See updates.

## Environment
- PHP Version: 7.2.4
- NGINX: 1.12.2
- Laravel Version:  5.6
- LaravelCaffeine Version: 0.6.8

## Stack Trace

Unavailable.

**Comment by ItaloBC** [comment]
## Update 2:

Removed Caffeine. Went to `web-php` and added my own drip route:

```php

Route::get('/drip-route', function() {
    return response(null, 204);
});
```

Then I made a GET with Axios to that point (which includes a CSRF token in the meta), and the form didn't expire.

Back to installing caffeine and see where the chain fails.

**Comment by ItaloBC** [comment]
## Update 3 (This is weird)

Installed Caffeine, 

I deleted the route declaration in `/routes/web.php` of this package:

```php
// Route::get($dripRoute, Drip::class.'@drip');
``` 

Then I added the default route in my `web.php`, at root.

```php
Route::get('/genealabs/laravel-caffeine/drip', function() {
    return response(null, 204);
});
```

**Success**. Forms doesn't expire.

But it won't work if the route is declared using the `web.php` of this package.

So, *something* is interfering with the route that Caffeine is declaring, but at glance everything is clean.

**Comment by ItaloBC** [comment]
## Update 4 (more weird things).

Adding the same code I added in my `web.php` in the `route/web.php` package gives the same problem:

```php
// Route::get($dripRoute, Drip::class.'@drip');

Route::get('/genealabs/laravel-caffeine/drip', function() {
    return response(null, 204);
});
```

**Comment by mikebronner** [comment]
Hi guys, thanks for reporting this. I will check this out soon -- I'm currently swamped with work, but hope to get to it over the weekend.

**Comment by s21825** [comment]
I've also encountered this issue (or something very similar).

PHP Version: 7.2.7
NGINX: nginx/1.14.0 (Ubuntu)
Laravel Version: 5.6
LaravelCaffeine Version: ^0.6.11

I noticed that the session was still expiring on an idle form and research led me here. After trying the workaround of creating a route in my web.php file to catch the drip requests, the session is no longer expiring.

From the network tab on Chrome devtools the only difference I can see is that when the drips are handled by the overridden route the following response headers get sent:

Set-Cookie: XSRF-TOKEN={snip}; expires={snip}; Max-Age=7200; path=/
Set-Cookie: {snip}_session={snip}; expires={snip}; Max-Age=7200; path=/; httponly

When the default route handles the drip those response headers are absent. Everything else looks identical though.

I'm up and running with the overridden route entry though so thanks for posting that workaround!

**Comment by mikebronner** [comment]
@s21825 @ItaloBC Please add this bit of code to your form page, and let me know what the output is:

```php
<?php dd(php_sapi_name()); ?>
```

**Comment by s21825** [comment]
This is what I get:

"fpm-fcgi"

**Comment by mikebronner** [comment]
@s21825 that should work. Can you try the latest update from today and see if the problem still persists?

**Comment by s21825** [comment]
I just did a quick test by setting my session lifetime to 6 minutes with the default drip interval of 5 minutes. After three drips I still had an active session. So it appears to be working as expected with the latest version. I'll leave things idle for a few hours and check again but so far so good! Thanks for following up.

**Comment by s21825** [comment]
After further investigation, the session is still expiring with the new release. I'll have to see if I can put together a public project to share with the issue present as I am not able to share my current project.

**Comment by mikebronner** [comment]
@MoogyG can you also run this command in your blade view with your form:
```php
<?php dd(php_sapi_name()); ?>
```

**Comment by MoogyG** [comment]
"fpm-fcgi"

I am using laradock on ubuntu 16.04.

**Comment by MoogyG** [comment]
Found something, dd($this->middlewareGroupExists('web')); give me false in boot method

**Comment by mikebronner** [comment]
@MoogyG that needs to be checked for backward compatibility. The command I provided above directly relates to that middleware check, but your's shouldn't be reporting false. Can you follow the chain and see what line of code causes it to be false on your system?

Thanks!

**Comment by MoogyG** [comment]
```php 
$routes = collect(app('router')->getRoutes()->getRoutes());
dd($routes);
```
only report "barryvdh/laravel-debugbar" routes that is not using web middleware.

Is there a problem with laravel auto package discovery? If you are the first service loaded, you can't see other routes, i don't think it's a good way.

**Comment by mikebronner** [comment]
By any chance are you using route closures? Also, would you mind pasting your `routes/web.php` file content here? Thanks!

**Comment by MoogyG** [comment]
none route closures until I wrote to test:

`Route::get( 'caffeine/drip', function() {
    return response(null, 204);
});`

And i am not authorized to do that :)

**Comment by mazen1985** [comment]
Any updates here, I have same issue the package is still dripping but the session still keeping expired.

**Comment by liyu001989** [comment]
laravel 5.8 same issue,  `middlewareGroupExists` return false  because   `$routes = collect(app('router')->getRoutes()->getRoutes());` is empty array。

**Comment by smirnov-tk** [comment]
Same here.
Why don't you use **hasMiddlewareGroup** function of the Router if it is available? It's 5.4+
And it can see my 'web' group
[Laravel API](https://laravel.com/api/5.8/Illuminate/Routing/Router.html#method_hasMiddlewareGroup)

**Comment by mikebronner** [comment]
@smirnov-tk @mazen1985 @MoogyG @liyu001989 Sorry for the delay on this. Thanks for the suggestion @smirnov-tk, I will take a look.

**Comment by mikebronner** [comment]
@smirnov-tk @mazen1985 @MoogyG @liyu001989 I finally got around to updating the code with @smirnov-tk's suggestion. Please try release 0.8.2 or newer and let me know how it works.
