### ISSUE TITLE
catastrophic backtracking

### ISSUE THREAD

**Issue by juandi** [GeneaLabs/laravel-caffeine#92]
## Expected Behavior
detect <input name="_token"
## Acutal Behavior
donest detect <input name="_token"
## Environment
- PHP Version:  7
- Laravel Version: 56 
- LaravelCaffeine Version:  0.6.8

## Stack Trace
Catastrophic backtracking qhen test the regex in regex101. If I am on a edit form with method = put, the regex does´t detect the _token input field. You can test it:
<form method="POST" action="https://domain/en/cms/videos/25" accept-charset="UTF-8" class="form form-horizontal form-label-left" data-type="ajax" id="frmVideo"><input name="_method" type="hidden" value="PUT"><input name="_token" type="hidden" value="YTBmhb3RfsLKoMlaUAigIn4kbPw3BhU9dP64CeBB">
If remove the _method input, then the regex detect _token without problems.

Thanks for every thing

**Comment by mikebronner** [comment]
Please provide an Some HTML with the form and elements that are causing this issue so I can easily replicate the issue. Thanks for reporting this!

**Comment by juandi** [comment]
Hi mike!

thanks for your fast reply.  Here is a HTML source that make the error:
`

                    <form method="POST" action="https://webserver/en/cms/news/2" accept-charset="UTF-8" class="form form-horizontal form-label-left" data-type="ajax"><input name="_method" type="hidden" value="PUT"><input name="_token" type="hidden" value="mhDCFj9Zqk3sOijfSVOJdFyO5HEHBB2L4GDutGbm">
                            </form>
