### ISSUE TITLE
Issues with "let" in Safari 9

### ISSUE THREAD

**Issue by spaceemotion** [GeneaLabs/laravel-caffeine#94]
## Expected Behavior
No Errors

## Acutal Behavior
Hundreds of Client-Side Errors (collected via Sentry)

## Environment
- PHP Version: 7.2
- Laravel Version: 5.5.40
- LaravelCaffeine Version: 0.6.8

## Stack Trace
`SyntaxError: Unexpected identifier 'lastCheck'` (https://github.com/GeneaLabs/laravel-caffeine/blob/master/resources/views/script.blade.php#L2)

![image](https://user-images.githubusercontent.com/429147/39971159-ffe5ce32-56f6-11e8-8b35-6f99830afb68.png)

-----

First of all, thank you for this wonderful package! Why this is not an opt-in solution our of the box with Laravel, I don't know.

I'm currently ignoring the errors in hope of seeing dwindling usage numbers of that Browser (Safari 9), but it seems like people just don't upgrade… 

Since it seems to not support the "let" keyword, would it be possible to change the template to use "var" instead? This should also [cover IE 10 and the like](https://caniuse.com/#search=let). I can also provide a PR if you're currently out of time. Cheers!

Edit: Just saw that there's already a PR open for this… https://github.com/GeneaLabs/laravel-caffeine/pull/86

**Comment by mikebronner** [comment]
Thanks for reporting this! Fix coming right up.
